load('config.js');

function execute() {
    return Response.success([
        { title: "Tiên Hiệp", input: "/the-loai/tien-hiep/", script: "gen.js" },
        { title: "Huyền Huyễn", input: "/the-loai/huyen-huyen/", script: "gen.js" },
        { title: "Đô Thị", input: "/the-loai/do-thi/", script: "gen.js" },
        { title: "Đồng Nhân", input: "/the-loai/dong-nhan/", script: "gen.js" },
        { title: "Hệ Thống", input: "/the-loai/he-thong/", script: "gen.js" },
        { title: "Khoa Huyễn", input: "/the-loai/khoa-huyen/", script: "gen.js" },
        { title: "Kiếm Hiệp", input: "/the-loai/kiem-hiep/", script: "gen.js" },
        { title: "Võng Du", input: "/the-loai/vong-du/", script: "gen.js" },
        { title: "Ác Cảo", input: "/the-loai/ac-cao/", script: "gen.js" },
        { title: "Ái Tình", input: "/the-loai/ai-tinh/", script: "gen.js" },
        { title: "Bác Sĩ", input: "/the-loai/bac-si/", script: "gen.js" },
        { title: "Bàn Thờ", input: "/the-loai/ban-tho/", script: "gen.js" },
        { title: "Báo Thù", input: "/the-loai/bao-thu/", script: "gen.js" },
        { title: "Biến Thân", input: "/the-loai/bien-than/", script: "gen.js" },
        { title: "Bình tĩnh", input: "/the-loai/binh-tinh/", script: "gen.js" },
        { title: "Cá Mặn", input: "/the-loai/ca-man/", script: "gen.js" },
        { title: "Cạnh Kỹ", input: "/the-loai/canh-ky/", script: "gen.js" },
        { title: "Cáo Tiếu Thổ Tào", input: "/the-loai/cao-tieu-tho-tao/", script: "gen.js" },
        { title: "Cao Võ Thế Giới", input: "/the-loai/cao-vo-the-gioi/", script: "gen.js" },
        { title: "Chiến Tranh", input: "/the-loai/chien-tranh/", script: "gen.js" },
        { title: "Chư Thiên Vạn Giới", input: "/the-loai/chu-thien-van-gioi/", script: "gen.js" },
        { title: "Chức Tràng", input: "/the-loai/chuc-trang/", script: "gen.js" },
        { title: "Chủng Điền", input: "/the-loai/chung-dien/", script: "gen.js" },
        { title: "Chuyển Thế", input: "/the-loai/chuyen-the/", script: "gen.js" },
        { title: "Cổ Đại", input: "/the-loai/co-dai/", script: "gen.js" },
        { title: "Cổ Đại Ngôn Tình", input: "/the-loai/co-dai-ngon-tinh/", script: "gen.js" },
        { title: "Cổ Điển Tiên Hiệp", input: "/the-loai/co-dien-tien-hiep/", script: "gen.js" },
        { title: "Cổ Ngu", input: "/the-loai/co-ngu/", script: "gen.js" },
        { title: "Cô Nhi", input: "/the-loai/co-nhi/", script: "gen.js" },
        { title: "Cổ Tiên Hiệp", input: "/the-loai/co-tien-hiep/", script: "gen.js" },
        { title: "Cơ Trí", input: "/the-loai/co-tri/", script: "gen.js" },
        { title: "Cổ Võ Cơ Giáp", input: "/the-loai/co-vo-co-giap/", script: "gen.js" },
        { title: "Cổ Võ Tương Lai", input: "/the-loai/co-vo-tuong-lai/", script: "gen.js" },
        { title: "Cơm Mềm", input: "/the-loai/com-mem/", script: "gen.js" },
        { title: "Công Sở", input: "/the-loai/cong-so/", script: "gen.js" },
        { title: "Cung Đấu", input: "/the-loai/cung-dau/", script: "gen.js" },
        { title: "Cung Vi Trạch Đấu", input: "/the-loai/cung-vi-trach-dau/", script: "gen.js" },
        { title: "Cường Giả Hồi Quy", input: "/the-loai/cuong-gia-hoi-quy/", script: "gen.js" },
        { title: "Dã Sử", input: "/the-loai/da-su/", script: "gen.js" },
        { title: "Đặc Chủng Binh", input: "/the-loai/dac-chung-binh/", script: "gen.js" },
        { title: "Đặc Công", input: "/the-loai/dac-cong/", script: "gen.js" },
        { title: "Đan dược", input: "/the-loai/dan-duoc/", script: "gen.js" },
        { title: "Dân Gian Truyền Thuyết", input: "/the-loai/dan-gian-truyen-thuyet/", script: "gen.js" },
        { title: "Đàn Xuyên", input: "/the-loai/dan-xuyen/", script: "gen.js" },
        { title: "Đạo Mộ", input: "/the-loai/dao-mo/", script: "gen.js" },
        { title: "Dị Giới", input: "/the-loai/di-gioi/", script: "gen.js" },
        { title: "Dị năng", input: "/the-loai/di-nang/", script: "gen.js" },
        { title: "Dị Thế", input: "/the-loai/di-the/", script: "gen.js" },
        { title: "Dị Thế Đại Lục", input: "/the-loai/di-the-dai-luc/", script: "gen.js" },
        { title: "Dị Thú", input: "/the-loai/di-thu/", script: "gen.js" },
        { title: "Dị thuật siêu năng", input: "/the-loai/di-thuat-sieu-nang/", script: "gen.js" },
        { title: "Điềm Đạm", input: "/the-loai/diem-dam/", script: "gen.js" },
        { title: "Diễn Sinh Đồng Nhân", input: "/the-loai/dien-sinh-dong-nhan/", script: "gen.js" },
        { title: "Điện Tử Cạnh Kỹ", input: "/the-loai/dien-tu-canh-ky/", script: "gen.js" },
        { title: "Điền Văn", input: "/the-loai/dien-van/", script: "gen.js" },
        { title: "Điền Viên", input: "/the-loai/dien-vien/", script: "gen.js" },
        { title: "Đô Thị Dị Năng", input: "/the-loai/do-thi-di-nang/", script: "gen.js" },
        { title: "Đô Thị Sinh Hoạt", input: "/the-loai/do-thi-sinh-hoat/", script: "gen.js" },
        { title: "Đoản Văn", input: "/the-loai/doan-van/", script: "gen.js" },
        { title: "Đông Phương", input: "/the-loai/dong-phuong/", script: "gen.js" },
        { title: "Đông Phương Huyền Huyễn", input: "/the-loai/dong-phuong-huyen-huyen/", script: "gen.js" },
        { title: "Du Hí", input: "/the-loai/du-hi/", script: "gen.js" },
        { title: "Du Hí Dị Giới", input: "/the-loai/du-hi-di-gioi/", script: "gen.js" },
        { title: "Dũng Mãnh", input: "/the-loai/dung-manh/", script: "gen.js" },
        { title: "Dương Quang", input: "/the-loai/duong-quang/", script: "gen.js" },
        { title: "Dưỡng Thành", input: "/the-loai/duong-thanh/", script: "gen.js" },
        { title: "Game of Thrones", input: "/the-loai/game-of-thrones/", script: "gen.js" },
        { title: "Giá Không Lịch Sử", input: "/the-loai/gia-khong-lich-su/", script: "gen.js" },
        { title: "Giám Bảo", input: "/the-loai/giam-bao/", script: "gen.js" },
        { title: "Giảo Hoạt", input: "/the-loai/giao-hoat/", script: "gen.js" },
        { title: "Góc Nhìn Nam", input: "/the-loai/goc-nhin-nam/", script: "gen.js" },
        { title: "Góc Nhìn Nữ", input: "/the-loai/goc-nhin-nu/", script: "gen.js" },
        { title: "Hắc Ám Huyễn Tưởng", input: "/the-loai/hac-am-huyen-tuong/", script: "gen.js" },
        { title: "Hài Hước", input: "/the-loai/hai-huoc/", script: "gen.js" },
        { title: "Hàn Môn", input: "/the-loai/han-mon/", script: "gen.js" },
        { title: "Hào Môn Thế Gia", input: "/the-loai/hao-mon-the-gia/", script: "gen.js" },
        { title: "Hệ thống lưu", input: "/the-loai/he-thong-luu/", script: "gen.js" },
        { title: "Hiện Đại Ma Pháp", input: "/the-loai/hien-dai-ma-phap/", script: "gen.js" },
        { title: "Hiện Đại Ngôn Tình", input: "/the-loai/hien-dai-ngon-tinh/", script: "gen.js" },
        { title: "Hiện Đại Tu Chân", input: "/the-loai/hien-dai-tu-chan/", script: "gen.js" },
        { title: "Hoàn thành", input: "/the-loai/hoan-thanh/", script: "gen.js" },
        { title: "Học sinh", input: "/the-loai/hoc-sinh/", script: "gen.js" },
        { title: "Học Viện", input: "/the-loai/hoc-vien/", script: "gen.js" },
        { title: "Hồng Hoang", input: "/the-loai/hong-hoang/", script: "gen.js" },
        { title: "Hồng Lâu", input: "/the-loai/hong-lau/", script: "gen.js" },
        { title: "Hư Nghĩ Võng Du", input: "/the-loai/hu-nghi-vong-du/", script: "gen.js" },
        { title: "Huyền Ảo", input: "/the-loai/huyen-ao/", script: "gen.js" },
        { title: "Huyền Học", input: "/the-loai/huyen-hoc/", script: "gen.js" },
        { title: "Huyền Huyễn Ngôn Tình", input: "/the-loai/huyen-huyen-ngon-tinh/", script: "gen.js" },
        { title: "Huyền Nghi", input: "/the-loai/huyen-nghi/", script: "gen.js" },
        { title: "Huyền Nghi Thần Quái", input: "/the-loai/huyen-nghi-than-quai/", script: "gen.js" },
        { title: "Huyễn Tưởng Tu Tiên", input: "/the-loai/huyen-tuong-tu-tien/", script: "gen.js" },
        { title: "Khác", input: "/the-loai/khac/", script: "gen.js" },
        { title: "Khác loại huyễn tưởng", input: "/the-loai/khac-loai-huyen-tuong/", script: "gen.js" },
        { title: "Khế Ước", input: "/the-loai/khe-uoc/", script: "gen.js" },
        { title: "Khoa Huyễn Không Gian", input: "/the-loai/khoa-huyen-khong-gian/", script: "gen.js" },
        { title: "Kiếm Dữ Ma Pháp", input: "/the-loai/kiem-du-ma-phap/", script: "gen.js" },
        { title: "Kiên Nghị", input: "/the-loai/kien-nghi/", script: "gen.js" },
        { title: "Kiêu Ngạo", input: "/the-loai/kieu-ngao/", script: "gen.js" },
        { title: "Kinh Thương", input: "/the-loai/kinh-thuong/", script: "gen.js" },
        { title: "Kinh Thương Chủng Điền", input: "/the-loai/kinh-thuong-chung-dien/", script: "gen.js" },
        { title: "Kỳ Ảo", input: "/the-loai/ky-ao/", script: "gen.js" },
        { title: "Kỳ Diệu Thế Giới", input: "/the-loai/ky-dieu-the-gioi/", script: "gen.js" },
        { title: "Kỳ Huyễn", input: "/the-loai/ky-huyen/", script: "gen.js" },
        { title: "Kỹ Thuật", input: "/the-loai/ky-thuat/", script: "gen.js" },
        { title: "Lãnh Khốc", input: "/the-loai/lanh-khoc/", script: "gen.js" },
        { title: "Lão Gia", input: "/the-loai/lao-gia/", script: "gen.js" },
        { title: "Lão Sư", input: "/the-loai/lao-su/", script: "gen.js" },
        { title: "Lệ Chí", input: "/the-loai/le-chi/", script: "gen.js" },
        { title: "Lịch Sử", input: "/the-loai/lich-su/", script: "gen.js" },
        { title: "Lịch Sử Quân Sự", input: "/the-loai/lich-su-quan-su/", script: "gen.js" },
        { title: "Lịch Sử Quan Trường", input: "/the-loai/lich-su-quan-truong/", script: "gen.js" },
        { title: "Lịch Sử Thần Thoại", input: "/the-loai/lich-su-than-thoai/", script: "gen.js" },
        { title: "Light Novel", input: "/the-loai/light-novel/", script: "gen.js" },
        { title: "Linh Dị", input: "/the-loai/linh-di/", script: "gen.js" },
        { title: "Linh Khí Khôi Phục", input: "/the-loai/linh-khi-khoi-phuc/", script: "gen.js" },
        { title: "LOL", input: "/the-loai/lol/", script: "gen.js" },
        { title: "Long", input: "/the-loai/long/", script: "gen.js" },
        { title: "Lưỡng Tấn Tuỳ Đường", input: "/the-loai/luong-tan-tuy-duong/", script: "gen.js" },
        { title: "Lưỡng Tống Nguyên Minh", input: "/the-loai/luong-tong-nguyen-minh/", script: "gen.js" },
        { title: "Luyện Công", input: "/the-loai/luyen-cong/", script: "gen.js" },
        { title: "Ma Pháp", input: "/the-loai/ma-phap/", script: "gen.js" },
        { title: "Ma Pháp Huyễn Tình", input: "/the-loai/ma-phap-huyen-tinh/", script: "gen.js" },
        { title: "Ma Thú", input: "/the-loai/ma-thu/", script: "gen.js" },
        { title: "Mary Sue", input: "/the-loai/mary-sue/", script: "gen.js" },
        { title: "Mạt Thế", input: "/the-loai/mat-the/", script: "gen.js" },
        { title: "Mạt Thế Nguy Cơ", input: "/the-loai/mat-the-nguy-co/", script: "gen.js" },
        { title: "Minh Tinh", input: "/the-loai/minh-tinh/", script: "gen.js" },
        { title: "Mỹ Thực", input: "/the-loai/my-thuc/", script: "gen.js" },
        { title: "Ngôi Thứ Nhất", input: "/the-loai/ngoi-thu-nhat/", script: "gen.js" },
        { title: "Ngôn Tình", input: "/the-loai/ngon-tinh/", script: "gen.js" },
        { title: "Ngọt", input: "/the-loai/ngot/", script: "gen.js" },
        { title: "Ngọt Sủng", input: "/the-loai/ngot-sung/", script: "gen.js" },
        { title: "Ngu Ngốc", input: "/the-loai/ngu-ngoc/", script: "gen.js" },
        { title: "Ngu Nhạc Minh Tinh", input: "/the-loai/ngu-nhac-minh-tinh/", script: "gen.js" },
        { title: "Ngự Thú", input: "/the-loai/ngu-thu/", script: "gen.js" },
        { title: "Ngược", input: "/the-loai/nguoc/", script: "gen.js" },
        { title: "Nguyên Sinh Huyễn Tưởng", input: "/the-loai/nguyen-sinh-huyen-tuong/", script: "gen.js" },
        { title: "Nhẹ Nhàng", input: "/the-loai/nhe-nhang/", script: "gen.js" },
        { title: "Nhẹ nhõm", input: "/the-loai/nhe-nhom/", script: "gen.js" },
        { title: "Nhiệt Huyết", input: "/the-loai/nhiet-huyet/", script: "gen.js" },
        { title: "Nhiều Converter", input: "/the-loai/nhieu-converter/", script: "gen.js" },
        { title: "Nữ Cường", input: "/the-loai/nu-cuong/", script: "gen.js" },
        { title: "Nữ Hiệp", input: "/the-loai/nu-hiep/", script: "gen.js" },
        { title: "Phàm Nhân", input: "/the-loai/pham-nhan/", script: "gen.js" },
        { title: "Phản Phái", input: "/the-loai/phan-phai/", script: "gen.js" },
        { title: "Pháp sư", input: "/the-loai/phap-su/", script: "gen.js" },
        { title: "Phế Tài", input: "/the-loai/phe-tai/", script: "gen.js" },
        { title: "Phúc Hắc", input: "/the-loai/phuc-hac/", script: "gen.js" },
        { title: "Phương Tây", input: "/the-loai/phuong-tay/", script: "gen.js" },
        { title: "Quân Nhân", input: "/the-loai/quan-nhan/", script: "gen.js" },
        { title: "Quân Sự", input: "/the-loai/quan-su/", script: "gen.js" },
        { title: "Quan Trường", input: "/the-loai/quan-truong/", script: "gen.js" },
        { title: "Quần Xuyên", input: "/the-loai/quan-xuyen/", script: "gen.js" },
        { title: "Quỷ Bí Huyền Nghi", input: "/the-loai/quy-bi-huyen-nghi/", script: "gen.js" },
        { title: "Quỷ Quái", input: "/the-loai/quy-quai/", script: "gen.js" },
        { title: "Sắc", input: "/the-loai/sac/", script: "gen.js" },
        { title: "Sắc Hiệp", input: "/the-loai/sac-hiep/", script: "gen.js" },
        { title: "Sảng Văn", input: "/the-loai/sang-van/", script: "gen.js" },
        { title: "Sát Thủ", input: "/the-loai/sat-thu/", script: "gen.js" },
        { title: "Sau Màn", input: "/the-loai/sau-man/", script: "gen.js" },
        { title: "Siêu Cấp Khoa Kỹ", input: "/the-loai/sieu-cap-khoa-ky/", script: "gen.js" },
        { title: "Sử Thi Kỳ Huyễn", input: "/the-loai/su-thi-ky-huyen/", script: "gen.js" },
        { title: "Sủng", input: "/the-loai/sung/", script: "gen.js" },
        { title: "Sủng Vật", input: "/the-loai/sung-vat/", script: "gen.js" },
        { title: "Tần Hán Tam Quốc", input: "/the-loai/tan-han-tam-quoc/", script: "gen.js" },
        { title: "Tạp Phiến", input: "/the-loai/tap-phien/", script: "gen.js" },
        { title: "Tất cả", input: "/the-loai/tat-ca/", script: "gen.js" },
        { title: "Tây Du", input: "/the-loai/tay-du/", script: "gen.js" },
        { title: "Tây Phương", input: "/the-loai/tay-phuong/", script: "gen.js" },
        { title: "Tây Phương Kỳ Huyễn", input: "/the-loai/tay-phuong-ky-huyen/", script: "gen.js" },
        { title: "Thám Hiểm Sinh Tồn", input: "/the-loai/tham-hiem-sinh-ton/", script: "gen.js" },
        { title: "Thần Thoại Tu Chân", input: "/the-loai/than-thoai-tu-chan/", script: "gen.js" },
        { title: "Thanh Xuân Vườn Trường", input: "/the-loai/thanh-xuan-vuon-truong/", script: "gen.js" },
        { title: "Thể Dục Cạnh Kỹ", input: "/the-loai/the-duc-canh-ky/", script: "gen.js" },
        { title: "Thế Giới Tương Lai", input: "/the-loai/the-gioi-tuong-lai/", script: "gen.js" },
        { title: "Thì không xuyên toa", input: "/the-loai/thi-khong-xuyen-toa/", script: "gen.js" },
        { title: "Thiên Tài", input: "/the-loai/thien-tai/", script: "gen.js" },
        { title: "Thiết Huyết", input: "/the-loai/thiet-huyet/", script: "gen.js" },
        { title: "Thời Không Xuyên Toa", input: "/the-loai/thoi-khong-xuyen-toa/", script: "gen.js" },
        { title: "Thủ Du", input: "/the-loai/thu-du/", script: "gen.js" },
        { title: "Thục Sơn", input: "/the-loai/thuc-son/", script: "gen.js" },
        { title: "Thương Chiến Chức Tràng", input: "/the-loai/thuong-chien-chuc-trang/", script: "gen.js" },
        { title: "Tiên Hiệp Kỳ Duyên", input: "/the-loai/tien-hiep-ky-duyen/", script: "gen.js" },
        { title: "Tiến Hóa Biến Dị", input: "/the-loai/tien-hoa-bien-di/", script: "gen.js" },
        { title: "Tiên Lữ Kỳ Duyên", input: "/the-loai/tien-lu-ky-duyen/", script: "gen.js" },
        { title: "Tiểu thuyết", input: "/the-loai/tieu-thuyet/", script: "gen.js" },
        { title: "Tinh Tế Văn Minh", input: "/the-loai/tinh-te-van-minh/", script: "gen.js" },
        { title: "Tình Yêu", input: "/the-loai/tinh-yeu/", script: "gen.js" },
        { title: "Toàn Dân", input: "/the-loai/toan-dan/", script: "gen.js" },
        { title: "Trạch Nam", input: "/the-loai/trach-nam/", script: "gen.js" },
        { title: "Trận Pháp", input: "/the-loai/tran-phap/", script: "gen.js" },
        { title: "Tranh Phách", input: "/the-loai/tranh-phach/", script: "gen.js" },
        { title: "Triệu Hoán", input: "/the-loai/trieu-hoan/", script: "gen.js" },
        { title: "Trinh Thám", input: "/the-loai/trinh-tham/", script: "gen.js" },
        { title: "Trinh Tham Thôi Lý", input: "/the-loai/trinh-tham-thoi-ly/", script: "gen.js" },
        { title: "Trọng Sinh", input: "/the-loai/trong-sinh/", script: "gen.js" },
        { title: "Trùng Sinh", input: "/the-loai/trung-sinh/", script: "gen.js" },
        { title: "Truyện convert", input: "/the-loai/truyen-convert/", script: "gen.js" },
        { title: "Truyện Ngược", input: "/the-loai/truyen-nguoc/", script: "gen.js" },
        { title: "Truyện Teen", input: "/the-loai/truyen-teen/", script: "gen.js" },
        { title: "Truyền Thuyết", input: "/the-loai/truyen-thuyet/", script: "gen.js" },
        { title: "Tu Chân", input: "/the-loai/tu-chan/", script: "gen.js" },
        { title: "Tu Chân Văn Minh", input: "/the-loai/tu-chan-van-minh/", script: "gen.js" },
        { title: "Tu Tiên", input: "/the-loai/tu-tien/", script: "gen.js" },
        { title: "Tùy Thân", input: "/the-loai/tuy-than/", script: "gen.js" },
        { title: "Vả Mặt", input: "/the-loai/va-mat/", script: "gen.js" },
        { title: "Vị Diện", input: "/the-loai/vi-dien/", script: "gen.js" },
        { title: "Viễn Cổ Hồng Hoang", input: "/the-loai/vien-co-hong-hoang/", script: "gen.js" },
        { title: "Vô Địch", input: "/the-loai/vo-dich/", script: "gen.js" },
        { title: "Vô Hạn", input: "/the-loai/vo-han/", script: "gen.js" },
        { title: "Võ Hiệp", input: "/the-loai/vo-hiep/", script: "gen.js" },
        { title: "Võ Hiệp Huyễn Tưởng", input: "/the-loai/vo-hiep-huyen-tuong/", script: "gen.js" },
        { title: "Vô Sỉ", input: "/the-loai/vo-si/", script: "gen.js" },
        { title: "Vong Linh", input: "/the-loai/vong-linh/", script: "gen.js" },
        { title: "Vương Triều Tranh Bá", input: "/the-loai/vuong-trieu-tranh-ba/", script: "gen.js" },
        { title: "Xây Dựng Thế Lực", input: "/the-loai/xay-dung-the-luc/", script: "gen.js" },
        { title: "Xuyên Không", input: "/the-loai/xuyen-khong/", script: "gen.js" },
        { title: "Xuyên Nhanh", input: "/the-loai/xuyen-nhanh/", script: "gen.js" },
        { title: "Xuyên Qua", input: "/the-loai/xuyen-qua/", script: "gen.js" },
        { title: "Xuyên Sách", input: "/the-loai/xuyen-sach/", script: "gen.js" },
        { title: "Xuyên Toa", input: "/the-loai/xuyen-toa/", script: "gen.js" },
        { title: "Xuyên việt", input: "/the-loai/xuyen-viet/", script: "gen.js" },
        { title: "Yêu Đương Thường Ngày", input: "/the-loai/yeu-duong-thuong-ngay/", script: "gen.js" }
    ]);
}
